version: '2'
services:

  # database
  postgres:
    build: ./postgres
    ports:
      - 43967:5432

  redis:
    image: redis:3.0.7
    ports:
      - 6379:6379

  neo4j:
    image: neo4j:3.0.7
    ports:
      - 7474:7474
