version: '2'
services:

  # database
  postgres:
    build: ./postgres
    ports:
      - 40001:5432

  redis:
    image: redis:3.0.7
    ports:
      - 40003:6379

  neo4j:
    image: neo4j:3.0.7
    ports:
      - 40004:7474
      - 40005:7687
    environment:
      NEO4J_AUTH: none
