version: '2'
services:

  # database
  postgres:
    build: ./postgres
    ports:
      - 10001:5432

  redis:
    image: redis:3.0.7
    ports:
      - 10002:6379

  neo4j:
    image: neo4j:3.0.7
    ports:
      - 10003:7474
      - 10004:7687
    environment:
      NEO4J_AUTH: none


  # services
  api_server:
    image: tmtxt/tvgp-api-server:0.0.8
    ports:
      - 10005:4000
    environment:
      - POSTGRES_SERVER
      - POSTGRES_PORT
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_ENSURE_STORAGE
      - NEO4J_SERVER
      - NEO4J_PORT
      - API_SERVER_CODE_RELOADER
      - API_SERVER_STACKTRACE_DEPTH
      - API_SERVER_SEED_DATA
      - REDIS_SERVER
      - REDIS_PORT
      - DEFAULT_PERSON_PICTURE

  frontend:
    image: tmtxt/tvgp-frontend:0.0.3
    ports:
      - 3000:3000
    environment:
      - API_SERVER_SERVER
      - API_SERVER_PORT
