# Create new auth user
POST http://127.0.0.1:4000/api/auth-users
Content-Type: application/json
tvgp-auth-token: d2a66a8d-517a-491f-b7e2-bcb1c8ae7d63

{
  "user_role": "admin",
  "username": "test14",
  "email": "test14",
  "password": "hello",
  "helloAbc": "def"
}

# login
POST http://127.0.0.1:4000/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
