# Create new auth user
POST http://127.0.0.1:4000/api/auth-users
Content-Type: application/json
tvgp-auth-token: becf0f84-68aa-40f4-b920-8bd6b0ea6a63

{
  "user_role": "user",
  "username": "test100",
  "email": "test14",
  "password": "hello"
}

# Login
POST http://127.0.0.1:4000/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

# Logout
POST http://127.0.0.1:4000/api/logout
tvgp-auth-token: becf0f84-68aa-40f4-b920-8bd6b0ea6a63


# Get current user
GET http://127.0.0.1:4000/api/auth-users
tvgp-auth-token: 0c723fba-ce70-4551-a656-7365af47c309
