FROM elixir:1.3.4
MAINTAINER TruongTX

RUN apt-get update
RUN apt-get install -y inotify-tools ninja-build cmake

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN mix local.hex --force

COPY mix.exs /usr/src/app
COPY mix.lock /usr/src/app
RUN mix deps.get
RUN mix deps.compile
